WELCOME_TEXT = (
    "=================================\r\n"
    "           TelnetDM\r\n"
    "=================================\r\n"
    "\r\n"
    "Welcome back, adventurer.\r\n"
    "\r\n"
    "Commands:\r\n"
    "  look\r\n"
    "  inventory\r\n"
    "  go north/south\r\n"
    "  quit\r\n"
    "\r\n"
    "> "
)
